#!/bin/bash

# wpdbdump -- Dump a WordPress database to sql file.
#
# Copyright 2020 Rene Kreijveld - email@renekreijveld.nl
#
# This program is free software; you may redistribute it and/or modify it.
#
# Warning! This script needs the file wpfunctions. This has to be installed in the same directory as this script.
# This script also needs the WordPress CLI, see https://wp-cli.org/
#
# Version history
# 1.0 Initial version

# version
version=1.0

# general variables
mypath=$(cd $(dirname ${0}); pwd -P)
myname=$(basename ${0})
# include general functions
if [ ! -e ${mypath}/wpfunctions ]
then
	echo ""
	echo "Cannot continue: script wpfunctions not found."
	echo ""
	exit 1
else
	. ${mypath}/wpfunctions
fi

# display usage information
usage() {
	echo ""
	echo "${myname} version ${version}, written by Rene Kreijveld."
	echo ""
	echo "Usage: ${myname} [-s] [-h]"
	echo ""
	echo "-s Silent. No progress messages will be shown."
	echo "-h Help. Display this info."
	echo ""
	exit 0
}

# process the arguments
silent="no"
# process the arguments
while getopts sh opt; do
	case "${opt}" in
		s)  silent="yes"
			;;
		h)
			usage
			;;
		\?)
			echo "Invalid option: -$OPTARG" >&2
			exit 1
			;;
		:)
			echo "Option -$OPTARG requires an argument." >&2
			exit 1
			;;
	esac
done

if [ "${silent}" == "no" ]
then
	echo ""
	echo "${myname} version ${version}, written by Rene Kreijveld."
	echo ""
	echo "This is a WordPress ${wpversion} site. Starting database dump..."
fi

if [ "${silent}" == "no" ]
then
	wp --allow-root db export --add-drop-table
else
	wp --allow-root db export --add-drop-table --quiet
fi

if [ "${silent}" == "no" ]
then
	echo "Database dump created."
	ls -l *.sql
fi
