#!/bin/sh

# wpinfo -- Provide information about this WordPress installation.
#
# Copyright 2020 Rene Kreijveld - email@renekreijveld.nl
#
# This program is free software; you may redistribute it and/or modify it.
#
# Warning! This script needs the file jfunctions. This has to be installed in the same directory as this script.
#
# Version history
# 1.0 Initial version

# general variables
mypath=$(cd $(dirname ${0}); pwd -P)
myname=$(basename ${0})

# include general functions
if [ ! -e ${mypath}/wpfunctions ]
then
	echo ""
	echo "Cannot continue: script wpfunctions not found."
	echo ""
	exit 1
else
	. ${mypath}/wpfunctions
fi

# version
version=1.0

echo ""
echo "${myname} verion ${version}, written by Rene Kreijveld."
echo ""

# output information
echo "This WordPress website:"
echo "Sitename    :" $sitenameclean
echo "Version     :" $wpversion
echo "DB Name     :" $database
echo "DB User     :" $dbuser
echo "DB Password :" $password
echo "DB Host     :" $host
echo "DB Prefix   :" $prefix
echo "Path        :" `pwd`
