#!/bin/bash

# wplist -- Find WordPress instances on your (DirectAdmin based) server.
#
# Copyright 2020 Rene Kreijveld - email@renekreijveld.nl
#
# This program is free software; you may redistribute it and/or modify it.
#
# Warning! This script needs the file jfunctions. This has to be installed in the same directory as this script.
#
# Version history
# 1.0 Initial version

# define variables
version=1.0
mypath=$(cd $(dirname ${0}); pwd -P)
myname=$(basename ${0})
startdir=/home

# display usage information
usage() {
	echo ""
	echo "${myname} version ${version}, written by Rene Kreijveld."
	echo ""
	echo "Usage: ${myname} [-s] [-c] [-h] [-r release]"
	echo ""
	echo "-s Short. Only display path and WordPress version."
	echo "-r Release version. Only display information about WordPress sites with given release version, eg 5.5"
	echo "-c CSV. Output values in CSV format."
	echo "-h Help. Display this info."
	echo ""
	echo "Example usage:"
	echo ""
	echo "${myname}"
	echo "Outputs detailed information about Joomla websites found on this server."
	echo ""
	echo "${myname} -s -r 3.3"
	echo "Outputs short information about Joomla 3.3 websites found on this server."
	echo ""
	echo "${myname} -c > joomlasites.csv"
	echo "Outputs detailed information about Joomla websites in CSV format and writes result to the file joomlasites.csv."
	echo ""
	exit 0
}

# process the arguments
short="no"
csv="no"
releaseversion=
while getopts schr: opt
do
	case "${opt}" in
		s) short="yes";;
		r) releaseversion=$OPTARG;;
		c) csv="yes";;
		h) usage;;
		\?) usage;;
	esac
done

if [ "${csv}" == "no" ]
then
	if [ "${short}" == "no" ]
	then
		echo ""
		echo "${myname} version ${version}, written by Rene Kreijveld."
		echo ""
	fi
fi

if [ "${csv}" == "yes" ]
then
	echo "\"map\",\"name\",\"version\",\"database\",\"dbuser\",\"password\",\"host\",\"prefix\""
fi
for dir in $(find ${startdir} -maxdepth 4 -type d)
do
	if [ -f ${dir}/wp-config.php ]
	then
		# possible WordPress found
		cd ${dir}
		if [ "${csv}" == "no" ]
		then
			if [ "${short}" == "no" ]
			then
				echo Possible WordPress found in ${dir}
			fi
		fi

		# get WordPress information
		if [ ! -e ${mypath}/wpfunctions ]
		then
			echo ""
			echo "Cannot continue: script wpfunctions not found."
			echo ""
			exit 1
		else
			. ${mypath}/wpfunctions
		fi

		if [ ! -z "${releaseversion}" ] && [ "${releaseversion}" != "${wpversion}" ]
		then
			if [ "${csv}" == "no" ] && [ "${short}" == "no" ]
			then
				echo Skipping ${wpversion} is not ${releaseversion}
			fi
			continue;
		fi

		# output information
		if [ "${csv}" == "yes" ]
		then
			echo "\"${dir}\",\"${sitename}\",\"${wpversion}\",\"${database}\",\"${dbuser}\",\"${password}\",\"${host}\",\"${prefix}\""
		else
			if [ "${short}" == "no" ]
			then
				echo "WordPress information found:"
				echo "Sitename    : ${sitenameclean}"
				echo "Version     : ${wpversion}"
				echo "DB Name     : ${database}"
				echo "DB User     : ${dbuser}"
				echo "DB Password : ${password}"
				echo "DB Host     : ${host}"
				echo "DB Prefix   : ${prefix}"
				echo ""
			else
				echo "WordPress found in ${dir}"
				echo "Version: ${wpversion}"
				echo ""
			fi
		fi
	fi
done